export const weights: {
  energy: number;
  mood_vector: Record<MoodVectorKey, number>;
  other_features: Record<OtherFeaturesVectorKey, number>;
} = {
  energy: 3.0,
  mood_vector: {
    [`rock`]: 1.0,
    [`pop`]: 1.0,
    [`alternative`]: 1.0,
    [`indie`]: 1.0,
    [`electronic`]: 1.0,
    [`female vocalists`]: 0.5,
    [`dance`]: 1.0,
    [`00s`]: 0.75,
    [`alternative rock`]: 1.0,
    [`jazz`]: 1.0,
    [`beautiful`]: 0.3,
    [`metal`]: 1.0,
    [`chillout`]: 1.0,
    [`male vocalists`]: 0.5,
    [`classic rock`]: 1.0,
    [`soul`]: 1.0,
    [`indie rock`]: 1.0,
    [`Mellow`]: 0.75,
    [`electronica`]: 1.0,
    [`80s`]: 0.75,
    [`folk`]: 1.0,
    [`90s`]: 0.75,
    [`chill`]: 1.0,
    [`instrumental`]: 1.0,
    [`punk`]: 1.0,
    [`oldies`]: 0.5,
    [`blues`]: 1.0,
    [`hard rock`]: 1.0,
    [`ambient`]: 1.0,
    [`acoustic`]: 1.5,
    [`experimental`]: 1.0,
    [`female vocalist`]: 0.5,
    [`guitar`]: 0.75,
    [`Hip-Hop`]: 1.0,
    [`70s`]: 0.75,
    [`party`]: 1.0,
    [`country`]: 1.0,
    [`easy listening`]: 0.5,
    [`sexy`]: 0.5,
    [`catchy`]: 0.75,
    [`funk`]: 1.0,
    [`electro`]: 1.0,
    [`heavy metal`]: 1.0,
    [`Progressive rock`]: 1.0,
    [`60s`]: 0.75,
    [`rnb`]: 1.0,
    [`indie pop`]: 1.0,
    [`sad`]: 0.5,
    [`House`]: 1.0,
    [`happy`]: 0.5,
  },
  other_features: {
    aggressive: 1.5,
    danceable: 1.25,
    happy: 2.0,
    party: 1.5,
    relaxed: 1.5,
    sad: 2.0,
  },
};
